### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by fandean** [FanDean/web-demos#4]
当在主页和admin之间多次跳转时出现下面的错误：
```shell
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/home/fan/workspace/web-demos/node.js/blog/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/fan/workspace/web-demos/node.js/blog/node_modules/express/lib/response.js:170:12)
    at done (/home/fan/workspace/web-demos/node.js/blog/node_modules/express/lib/response.js:1004:10)
    at /home/fan/workspace/web-demos/node.js/blog/node_modules/swig/lib/swig.js:565:9
    at /home/fan/workspace/web-demos/node.js/blog/node_modules/swig/lib/swig.js:690:9
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```
“Can’t set headers after they are sent.” => “不能发送headers因为已经发送过一次了”

**Comment by fandean** [comment]
## 解决方法 

https://github.com/FanDean/web-demos/blob/bd1eb036de025093a0af405fc96e05fe204c54cb/node.js/blog/routers/admin.js#L10-L16
修改上面的代码为：
```javascript
router.use(function (req, res, next) {
    if (req.userInfo.isAdmin){
        next();
    } else {
        //非管理员
        res.send("<h1 style='color: red'>只有管理员才能进入后台管理界面</h1>");
    }
});
```

## 说明
涉及到Express的控制权转移的问题。
Express支持同一路径绑定多个路由响应函数。但是Express在处理路由规则时，会优先匹配先定义的路由规则，后面的相同的规则则被屏蔽。   

Express 提供了路由控制权转移的方法, 即回调函数的第三个参数 next ,通过调用`next()` , 会将路由控制权**转移给后面的规则**。

我们还可以使用 `next()` 实现中间件。上面的代码就实现了一个中间件。

**执行上面代码中的 `res.send()`时就已经输出过一次响应头，所以不应再执行 `next()` 方法。**
